DROP TABLE IF EXISTS Customer CASCADE ;


CREATE TABLE Customer(
id INT GENERATED by DEFAULT AS IDENTITY PRIMARY KEY,
citizen_No VARCHAR(11) NOT NULL,
name VARCHAR(30) UNIQUE NOT NULL,
surname VARCHAR(20) NOT NULL,
address VARCHAR(100)NOT NULL,
age INT NOT NULL ,
gender VARCHAR(6) NOT NULL,
profession VARCHAR(50) NOT NULL,
email VARCHAR(75) UNIQUE NOT NULL,
salary INT NOT NULL,
credit_Point INT NOT NULL
);



INSERT INTO Customer(citizen_No, name, surname,address, age, gender, profession, email, salary, credit_Point) VALUES('36698542345','Mehmet','Alagöz','Ankara',25,'male','Architect','malagoz@gmail.com',12000,1000),
                                                                           ('54786962314','Cem','Cihan','İstanbul',28,'male','Artist','cihanccc@gmail.com',30000,400),
                                                                           ('76720140200','Ayşe','Mor','Mersin',35,'female','School Teacher','aysemorr@gmail.com',8000,200),
                                                                           ('10154237586','Betül','Pembe','Gümüşhane',46,'female','Eye Doctor','pembebetul@gmail.com',15000,600),
                                                                           ('10052001135','Fatih','Doğanlar','İzmir',23,'male','Soccer Player','doganlarrff@gmail.com',1000000,1500),
                                                                           ('75868963211','Ali','Atmaz','Rize',45, 'male','Farmer', 'atmazali898@gmail.com',1000,100),
                                                                           ('56420123450','Hacer','Yıldırım','Ankara',32,'female','Cook','yildirimhacer@gmail.com',8000,600),
                                                                           ('74581243685','Şenay','Atılgan','Muğla', 29,'female','Pharmacist','atilgansenay@gmail.com',8500,700);

